version: "3"

tasks:
  auth:secret:
    desc: Generate AUTH_SECRET (base64, >= 32 bytes)
    cmds:
      - powershell -NoProfile -ExecutionPolicy Bypass -File scripts/gen-auth-secret.ps1

  geoip:download:
    desc: Download MaxMind GeoLite2 mmdb (requires MAXMIND_LICENSE_KEY)
    cmds:
      - powershell -NoProfile -ExecutionPolicy Bypass -File scripts/download-geoip.ps1

  run:
    desc: "Run gateway (defaults: local PG, remote NSQ)"
    cmds:
      - powershell -NoProfile -ExecutionPolicy Bypass -File scripts/run-gateway.ps1

  run:build:
    desc: Build then run gateway.exe
    cmds:
      - powershell -NoProfile -ExecutionPolicy Bypass -File scripts/run-gateway.ps1 -Build

  ui:install:
    desc: Install console deps (Bun)
    dir: web
    cmds:
      - bun install

  ui:dev:
    desc: Run console dev server
    dir: web
    cmds:
      - bun run dev

  ui:build:
    desc: Build console
    dir: web
    cmds:
      - bun run build

  docker:build:
    desc: "Build Docker image (default: aak1247/logtap:latest)"
    cmds:
      - docker build -f deploy/logtap/Dockerfile -t {{.IMG}}:{{.TAG}} .
    vars:
      TAG:
        sh: bash -c "echo ${TAG:-latest}"
      IMG:
        sh: bash -c "echo ${IMG:-aak1247/logtap}"

  docker:push:
    desc: "Push Docker image (default: aak1247/logtap:latest)"
    cmds:
      - docker push {{.IMG}}:{{.TAG}}
    vars:
      TAG:
        sh: bash -c "echo ${TAG:-latest}"
      IMG:
        sh: bash -c "echo ${IMG:-aak1247/logtap}"

  docker:build:push:
    desc: "Build and push Docker image (default: aak1247/logtap:latest)"
    cmds:
      - task: docker:build
      - task: docker:push

  test:it:
    desc: Run integration tests once (no cache)
    cmds:
      - go test ./sdks/go/logtap -run TestGoSDK_Integration_ -count=1
      - go test ./internal/integration -run TestIntegration_ -count=1
      # JS SDK batching/behavior sanity check (the JS end-to-end test runs inside TestIntegration_JSSDK_Gateway_SQLite)
      - powershell -NoProfile -Command "if (Get-Command node -ErrorAction SilentlyContinue) { node sdks/js/logtap/test/batching.test.mjs } else { Write-Host 'skip js sdk batching test (node not found)' }"

  test:unit:
    desc: Run unit tests (exclude internal/integration)
    cmds:
      - bash -lc "go test $(go list ./... | rg -v github.com/aak1247/logtap/internal/integration) -count=1"
